# Site settings
title: IISc-AHS Student Chapter
header-img: 
email: iisc.ahs@gmail.com
description: "The Indian Institute of Science(IISc), Bangalore - AHS International The Vertical Flight Technical Society Student Chapter. "
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username:  
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
